version: '3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    image: 'nginx:latest'
    ports:
      - '3050:80'
    depends_on:
      - frontend
      - backend
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - DATABASE="database.db"
  
  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
